import ClickChart from "../charts/ClickChart";
import DeviceChart from "../charts/DeviceChart";
import CountryChart from "../charts/CountryChart";

import jsPDF from "jspdf";

export default function Analytics() {

  const clickData = [
    { name: "Mon", clicks: 12 },
    { name: "Tue", clicks: 35 },
    { name: "Wed", clicks: 20 },
    { name: "Thu", clicks: 45 },
    { name: "Fri", clicks: 60 },
    { name: "Sat", clicks: 22 },
    { name: "Sun", clicks: 50 },
  ];

  const exportPDF = () => {

    const doc = new jsPDF();

    doc.setFontSize(20);
    doc.text(
      "Sniply AI Analytics Report",
      20,
      20
    );

    doc.setFontSize(12);

    doc.text(
      "Total Clicks: 244",
      20,
      40
    );

    doc.text(
      "Top Campaign: Summer Sale",
      20,
      50
    );

    doc.text(
      "Generated by Sniply AI",
      20,
      70
    );

    doc.save(
      "analytics-report.pdf"
    );
  };

  return (
    <div className="page-card">

      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          marginBottom: "25px",
        }}
      >

        <div>
          <h1>📈 Analytics</h1>

          <p>
            Performance overview of
            campaigns and shortened links.
          </p>
        </div>

        <button
          onClick={exportPDF}
        >
          Export PDF
        </button>

      </div>

      {/* KPI CARDS */}

      <div className="kpi-grid">

        <div className="stat-card">
          <h3>Total Clicks</h3>
          <h1>244</h1>
          <p>▲ 24%</p>
        </div>

        <div className="stat-card">
          <h3>Active Links</h3>
          <h1>18</h1>
          <p>▲ 12%</p>
        </div>

        <div className="stat-card">
          <h3>QR Downloads</h3>
          <h1>76</h1>
          <p>▲ 18%</p>
        </div>

        <div className="stat-card">
          <h3>Campaigns</h3>
          <h1>4</h1>
          <p>▲ 10%</p>
        </div>

      </div>

      {/* CLICK CHART */}

      <div
        className="chart-card"
        style={{
          marginTop: "25px",
        }}
      >

        <h2>
          Click Trend
        </h2>

        <ClickChart
          data={clickData}
        />

      </div>

      {/* DEVICE + COUNTRY */}

      <div
        style={{
          display: "grid",
          gridTemplateColumns:
            "1fr 1fr",
          gap: "20px",
          marginTop: "25px",
        }}
      >

        <div className="chart-card">

          <h2>
            Device Analytics
          </h2>

          <DeviceChart />

        </div>

        <div className="chart-card">

          <h2>
            Country Analytics
          </h2>

          <CountryChart />

        </div>

      </div>

      {/* TOP CAMPAIGNS */}

      <div
        className="chart-card"
        style={{
          marginTop: "25px",
        }}
      >

        <h2>
          Top Campaigns
        </h2>

        <table>

          <thead>
            <tr>
              <th>Campaign</th>
              <th>Clicks</th>
              <th>Status</th>
            </tr>
          </thead>

          <tbody>

            <tr>
              <td>Summer Sale</td>
              <td>1234</td>
              <td>Running</td>
            </tr>

            <tr>
              <td>Product Launch</td>
              <td>852</td>
              <td>Running</td>
            </tr>

            <tr>
              <td>College Event</td>
              <td>321</td>
              <td>Completed</td>
            </tr>

          </tbody>

        </table>

      </div>

    </div>
  );
}